"""Runtime limit defaults shared by room creation and data migrations."""

DEFAULT_MAX_MESSAGE_TOKENS = 900
DEFAULT_MAX_ROOM_TOKENS = 120000
DEFAULT_MAX_PHASE_ROUNDS = 3
DEFAULT_MAX_ACCOUNT_DAILY_TOKENS = 250000
DEFAULT_MAX_ACCOUNT_MONTHLY_TOKENS = 3000000
DEFAULT_MAX_CONSECUTIVE_AI_TURNS = 10

# Story scenes carry a larger prompt surface (world state, roster, private
# memory, relationships) and are expected to run until the user calls the cut.
SCENE_DEFAULT_MAX_MESSAGE_TOKENS = 1200
SCENE_DEFAULT_MAX_ROOM_TOKENS = 600000
SCENE_DEFAULT_MAX_PHASE_ROUNDS = 60
SCENE_DEFAULT_MAX_ACCOUNT_DAILY_TOKENS = 1000000
SCENE_DEFAULT_MAX_ACCOUNT_MONTHLY_TOKENS = 10000000
SCENE_DEFAULT_MAX_CONSECUTIVE_AI_TURNS = 120
